name: Format & Lint

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black flake8 isort
      - name: Run isort
        run: |
          isort . --check --profile "black"
      - name: Run black
        run: |
          black . --check --verbose
      - name: Run flake8
        run: |
          flake8 . --ignore=E501,W503
