name: Pylint

on: [push, pull_request]

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      - name: Run pylint
        run: |
          pylint $(git ls-files '*.py') --exit-zero --disable=missing-module-docstring,missing-function-docstring,missing-class-docstring,line-too-long,import-error,no-self-use,invalid-name,wrong-import-order,unused-argument,no-member,too-few-public-methods,too-many-public-methods,invalid-overridden-method
